### PR TITLE
Publish Microsoft Authored templates to azure samples browser

### PR DESCRIPTION
**Pull request by v-xuto**
Update metadata, and publish `APICenter-Analyzer` template to azure samples browser.

@hemarina and @justinyoo  for notification.

### CODE REVIEW

**Comment by justinyoo** [comment]
@pierceboggan @juliajuju93 Please review and merge.

**Review by hemarina — APPROVED** [review]

**Comment by justinyoo** [comment]
@pierceboggan Here's the update. Please take a look and merge

**Comment by v-xuto** [comment]
@pierceboggan  Could you help review this PR and merge it if it looks good? Thanks a lot.

**Review by pierceboggan — APPROVED** [review]
LGTM

**Comment by hemarina** [comment]
@v-xuto and I have an offline discussion on [sample status](https://github.com/MicrosoftDocs/samples/blob/main/Azure/apicenter-analyzer/.samples-status.json). Adding metadata at the bottom of Readme is not working. We will have to add it at the top.

**Pull request merged**
